params:
  - preprocess
  - train

stages:
  preprocess:
    cmd: python src/data_preprocessing.py params.yaml
    deps:
      - src/data_preprocessing.py
      - data/raw/Telco-Customer-Churn.csv
    params:
      - preprocess
    outs:
      - data/processed

  train:
    cmd: python src/model_trainer.py params.yaml
    deps:
      - src/model_trainer.py
      - data/processed
    params:
      - train
    outs:
      - models/random_forest_model.pkl
      - models/model_columns.json

  evaluate:
    cmd: python src/model_evaluation.py params.yaml
    deps:
      - src/model_evaluation.py
      - data/processed
      - models/random_forest_model.pkl
    params:
      - train
      - preprocess
    metrics:
      - metrics.json